### ISSUE TITLE
please consider tagging versions & doing releases

### ISSUE THREAD

**Issue by boegel** [google/cpu_features#12]
I assume this library is alpha-stage currently, but please tag versions/releases so people know exactly which revision of `cpu_features` they are currently using.

**Comment by gchatelet** [comment]
I'll update the documentation to reflect this but we prefer people to embed the library to prevent breakage due to API changes (i.e. compile and link statically). See abseil documentation [here](https://github.com/abseil/abseil-cpp/tree/master/CMake#recommended-usage--incorporate-abseil-into-an--cmake-project).

I don't plan to provide explicit versions or release for now.

**Comment by boegel** [comment]
*cough* https://www.youtube.com/watch?v=NSemlYagjIU *cough* ;-)

**Comment by vsoch** [comment]
*cough cough*

**Comment by gchatelet** [comment]
Fair enough. I understand there is a need for a versioning scheme.
Let's start with 0.1.0 : )

**Comment by boegel** [comment]
:+1:
