### ISSUE TITLE
Returning a stack-allocated value

### ISSUE THREAD

**Issue by camgunz** [google/cpu_features#6]
Hey!  The code at https://github.com/google/cpu_features/blob/master/src/cpuid_x86_clang.c#L21 (and in the other files) is returning a stack-allocated value, which I think is a problem?  I thought you needed an output parameter for that kind of thing.

EDIT: Oh it ends up copying it.  Well maybe not *bad* then, but not ideal either?

**Comment by gchatelet** [comment]
Yes it's a copy. Since this is a one time initialization I don't think there's an impact in copying a few bytes and it makes the usage much simpler.

Consider:
```
static const X86Features features = GetX86Info().features;
```

It would only copy `sizeof(X86Features)` which is currently 4 bytes, not a big deal in my opinion.

I'm closing this issue for now but feel free to reopen if you have any concerns.
